// <auto-generated />
using System;
using Koukei.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Koukei.Data.Migrations
{
    [DbContext(typeof(KoukeiDbContext))]
    [Migration("20260706103546_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Koukei.Data.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("DateModified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("Koukei.Data.Entities.BaseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Container")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("DateCreated")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DateLastRefreshed")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DateLastSaved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ForcedSortName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("IndexNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemKind")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastModified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentIndexNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductionYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SortName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TopParentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DateCreated");

                    b.HasIndex("Hash");

                    b.HasIndex("ItemKind");

                    b.HasIndex("Name");

                    b.HasIndex("NormalizedPath")
                        .IsUnique()
                        .HasFilter("\"NormalizedPath\" IS NOT NULL");

                    b.HasIndex("ParentId");

                    b.HasIndex("Path");

                    b.HasIndex("SortName");

                    b.HasIndex("TopParentId");

                    b.ToTable("Items", (string)null);

                    b.HasDiscriminator<int>("ItemKind");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Koukei.Data.Entities.DocumentInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsScanned")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WordCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("DocumentInfos", (string)null);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SortName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SortName");

                    b.ToTable("Genres", (string)null);
                });

            modelBuilder.Entity("Koukei.Data.Entities.ImageInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Channels")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ColorDepth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorSpace")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("HasAlpha")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ImageInfos", (string)null);
                });

            modelBuilder.Entity("Koukei.Data.Entities.ItemGenre", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("ItemGenres", (string)null);
                });

            modelBuilder.Entity("Koukei.Data.Entities.ItemPerson", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "PersonId", "Role", "SortOrder");

                    b.HasIndex("PersonId");

                    b.ToTable("ItemPeople", (string)null);
                });

            modelBuilder.Entity("Koukei.Data.Entities.ItemRating", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RatingId")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("ItemId", "RatingId");

                    b.HasIndex("RatingId");

                    b.ToTable("ItemRatings", (string)null);
                });

            modelBuilder.Entity("Koukei.Data.Entities.ItemStudio", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "StudioId", "SortOrder");

                    b.HasIndex("StudioId");

                    b.ToTable("ItemStudios", (string)null);
                });

            modelBuilder.Entity("Koukei.Data.Entities.ItemTag", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ItemTags", (string)null);
                });

            modelBuilder.Entity("Koukei.Data.Entities.LinkedImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BlurHash")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DateModified")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StudioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "ImageType", "ImageIndex")
                        .IsUnique()
                        .HasFilter("\"ItemId\" IS NOT NULL");

                    b.HasIndex("PersonId", "ImageType", "ImageIndex")
                        .IsUnique()
                        .HasFilter("\"PersonId\" IS NOT NULL");

                    b.HasIndex("StudioId", "ImageType", "ImageIndex")
                        .IsUnique()
                        .HasFilter("\"StudioId\" IS NOT NULL");

                    b.ToTable("LinkedImages", (string)null);
                });

            modelBuilder.Entity("Koukei.Data.Entities.LinkedText", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("DateModified")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GenreId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RatingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StudioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TagId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<int>("TextIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TextType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "TextType", "TextIndex")
                        .IsUnique()
                        .HasFilter("\"DocumentId\" IS NOT NULL");

                    b.HasIndex("GenreId", "TextType", "TextIndex")
                        .IsUnique()
                        .HasFilter("\"GenreId\" IS NOT NULL");

                    b.HasIndex("ImageId", "TextType", "TextIndex")
                        .IsUnique()
                        .HasFilter("\"ImageId\" IS NOT NULL");

                    b.HasIndex("ItemId", "TextType", "TextIndex")
                        .IsUnique()
                        .HasFilter("\"ItemId\" IS NOT NULL");

                    b.HasIndex("PersonId", "TextType", "TextIndex")
                        .IsUnique()
                        .HasFilter("\"PersonId\" IS NOT NULL");

                    b.HasIndex("RatingId", "TextType", "TextIndex")
                        .IsUnique()
                        .HasFilter("\"RatingId\" IS NOT NULL");

                    b.HasIndex("StudioId", "TextType", "TextIndex")
                        .IsUnique()
                        .HasFilter("\"StudioId\" IS NOT NULL");

                    b.HasIndex("TagId", "TextType", "TextIndex")
                        .IsUnique()
                        .HasFilter("\"TagId\" IS NOT NULL");

                    b.ToTable("LinkedTexts", (string)null);
                });

            modelBuilder.Entity("Koukei.Data.Entities.MediaLibraryRoot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("DateCreated")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DateLastSaved")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeSubdirectories")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastScanCompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastScanStartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastScanStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("LastScanStatus");

                    b.HasIndex("NormalizedPath")
                        .IsUnique();

                    b.ToTable("MediaLibraryRoots", (string)null);
                });

            modelBuilder.Entity("Koukei.Data.Entities.MediaLibraryScan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemsAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsDiscovered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsFailed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LibraryRootId")
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibraryRootId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("MediaLibraryScans", (string)null);
                });

            modelBuilder.Entity("Koukei.Data.Entities.MediaStreamInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BitRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codec")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<float?>("Duration")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsForced")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StreamIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StreamType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StreamType");

                    b.HasIndex("ItemId", "StreamIndex")
                        .IsUnique();

                    b.ToTable("MediaStreams", (string)null);

                    b.HasDiscriminator<int>("StreamType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Koukei.Data.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SortName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SortName");

                    b.ToTable("People", (string)null);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Source")
                        .IsUnique();

                    b.ToTable("Ratings", (string)null);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Studio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SortName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SortName");

                    b.ToTable("Studios", (string)null);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SortName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SortName");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Audio.Audio", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.BaseItem");

                    b.HasDiscriminator().HasValue(10);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Audio.AudioBook.AudioBookSeries", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.BaseItem");

                    b.Property<Guid?>("LinkedBookSeriesId")
                        .HasColumnType("TEXT");

                    b.HasIndex("LinkedBookSeriesId");

                    b.HasDiscriminator().HasValue(15);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Audio.Music.MusicAlbum", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.BaseItem");

                    b.Property<long?>("ReleaseDate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MusicAlbumReleaseDate");

                    b.HasDiscriminator().HasValue(13);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Audio.Radio.Radio", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.BaseItem");

                    b.HasDiscriminator().HasValue(17);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Document.Book.BookSeries", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.BaseItem");

                    b.HasDiscriminator().HasValue(10003);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Document.Document", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.BaseItem");

                    b.HasDiscriminator().HasValue(10000);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Document.Journal.Journal", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.BaseItem");

                    b.Property<string>("Issn")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublicationFrequency")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(10011);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Document.Magazine.Magazine", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.BaseItem");

                    b.Property<string>("Issn")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublicationFrequency")
                        .HasColumnType("INTEGER");

                    b.ToTable("Items", t =>
                        {
                            t.Property("Issn")
                                .HasColumnName("Magazine_Issn");

                            t.Property("PublicationFrequency")
                                .HasColumnName("Magazine_PublicationFrequency");
                        });

                    b.HasDiscriminator().HasValue(10005);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Document.Newspaper.Newspaper", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.BaseItem");

                    b.Property<string>("Issn")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublicationFrequency")
                        .HasColumnType("INTEGER");

                    b.ToTable("Items", t =>
                        {
                            t.Property("Issn")
                                .HasColumnName("Newspaper_Issn");

                            t.Property("PublicationFrequency")
                                .HasColumnName("Newspaper_PublicationFrequency");
                        });

                    b.HasDiscriminator().HasValue(10009);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Image.Comic.Comic", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.BaseItem");

                    b.Property<int?>("ChapterNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBook")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMagazine")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VolumeNumber")
                        .HasColumnType("INTEGER");

                    b.ToTable("Items", t =>
                        {
                            t.Property("IssueNumber")
                                .HasColumnName("Comic_IssueNumber");

                            t.Property("VolumeNumber")
                                .HasColumnName("Comic_VolumeNumber");
                        });

                    b.HasDiscriminator().HasValue(1005);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Image.Comic.ComicSeries", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.BaseItem");

                    b.HasDiscriminator().HasValue(1006);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Image.Illustration.IllustrationCollection", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.BaseItem");

                    b.HasDiscriminator().HasValue(1004);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Image.Image", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.BaseItem");

                    b.HasDiscriminator().HasValue(1000);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Image.Photo.PhotoAlbum", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.BaseItem");

                    b.HasDiscriminator().HasValue(1002);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Video.Movie.MovieSeries", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.BaseItem");

                    b.HasDiscriminator().HasValue(103);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Video.TV.TvSeason", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.BaseItem");

                    b.Property<string>("AirDays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("AirTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("TEXT");

                    b.HasIndex("SeriesId");

                    b.ToTable("Items", t =>
                        {
                            t.Property("SeriesId")
                                .HasColumnName("TvSeason_SeriesId");
                        });

                    b.HasDiscriminator().HasValue(105);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Video.TV.TvSeries", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.BaseItem");

                    b.HasDiscriminator().HasValue(106);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Video.Video", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.BaseItem");

                    b.HasDiscriminator().HasValue(100);
                });

            modelBuilder.Entity("Koukei.Data.Entities.AudioStreamInfo", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.MediaStreamInfo");

                    b.Property<int?>("BitDepth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Channels")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SampleRate")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Koukei.Data.Entities.VideoStreamInfo", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.MediaStreamInfo");

                    b.Property<string>("ColorDepth")
                        .HasColumnType("TEXT");

                    b.Property<float?>("FrameRate")
                        .HasColumnType("REAL");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsDolbyVision")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsHdr")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Audio.AudioBook.AudioBook", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.Audio.Audio");

                    b.Property<Guid?>("AudioBookSeriesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LinkedBookId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("AudioBookReleaseDate");

                    b.Property<int?>("VolumeNumber")
                        .HasColumnType("INTEGER");

                    b.HasIndex("AudioBookSeriesId");

                    b.HasIndex("LinkedBookId");

                    b.HasDiscriminator().HasValue(14);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Audio.AudioRecording", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.Audio.Audio");

                    b.Property<DateTime?>("RecordingDate")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(11);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Audio.Music.Music", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.Audio.Audio");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("MusicReleaseDate");

                    b.Property<int?>("TrackNumber")
                        .HasColumnType("INTEGER");

                    b.HasIndex("AlbumId");

                    b.HasDiscriminator().HasValue(12);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Audio.Radio.RadioEpisode", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.Audio.Audio");

                    b.Property<long?>("AirDate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RadioId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.HasIndex("RadioId");

                    b.HasDiscriminator().HasValue(16);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Document.Book.Book", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.Document.Document");

                    b.Property<Guid?>("BookSeriesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PublicationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("BookPublicationDate");

                    b.Property<int?>("VolumeNumber")
                        .HasColumnType("INTEGER");

                    b.HasIndex("BookSeriesId");

                    b.ToTable("Items", t =>
                        {
                            t.Property("VolumeNumber")
                                .HasColumnName("Book_VolumeNumber");
                        });

                    b.HasDiscriminator().HasValue(10002);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Document.SerialIssue", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.Document.Document");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("SerialPublicationDate");

                    b.Property<Guid?>("SerialId")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(10006);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Image.Illustration.Illustration", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.Image.Image");

                    b.HasDiscriminator().HasValue(1003);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Image.Photo.Photo", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.Image.Image");

                    b.HasDiscriminator().HasValue(1001);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Video.Movie.Movie", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.Video.Video");

                    b.Property<Guid?>("MovieSeriesId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PremiereDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("MoviePremiereDate");

                    b.HasIndex("MovieSeriesId");

                    b.HasDiscriminator().HasValue(102);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Video.MusicVideo", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.Video.Video");

                    b.Property<Guid?>("LinkedMusicId")
                        .HasColumnType("TEXT");

                    b.HasIndex("LinkedMusicId");

                    b.HasDiscriminator().HasValue(108);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Video.TV.TvEpisode", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.Video.Video");

                    b.Property<long?>("PremiereDate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TvEpisodePremiereDate");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("TEXT");

                    b.HasIndex("SeasonId");

                    b.HasIndex("SeriesId");

                    b.HasDiscriminator().HasValue(104);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Video.VideoRecording", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.Video.Video");

                    b.Property<DateTime?>("RecordingDate")
                        .HasColumnType("TEXT");

                    b.ToTable("Items", t =>
                        {
                            t.Property("RecordingDate")
                                .HasColumnName("VideoRecording_RecordingDate");
                        });

                    b.HasDiscriminator().HasValue(101);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Document.Journal.JournalIssue", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.Document.SerialIssue");

                    b.Property<int?>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("JournalId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VolumeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasIndex("JournalId");

                    b.ToTable("Items", t =>
                        {
                            t.Property("VolumeNumber")
                                .HasColumnName("JournalIssue_VolumeNumber");
                        });

                    b.HasDiscriminator().HasValue(10010);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Document.Magazine.MagazineIssue", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.Document.SerialIssue");

                    b.Property<int?>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MagazineId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasIndex("MagazineId");

                    b.ToTable("Items", t =>
                        {
                            t.Property("IssueNumber")
                                .HasColumnName("MagazineIssue_IssueNumber");

                            t.Property("Year")
                                .HasColumnName("MagazineIssue_Year");
                        });

                    b.HasDiscriminator().HasValue(10004);
                });

            modelBuilder.Entity("Koukei.Data.Entities.Document.Newspaper.NewspaperIssue", b =>
                {
                    b.HasBaseType("Koukei.Data.Entities.Document.SerialIssue");

                    b.Property<int?>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("NewspaperId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasIndex("NewspaperId");

                    b.ToTable("Items", t =>
                        {
                            t.Property("Year")
                                .HasColumnName("NewspaperIssue_Year");
                        });

                    b.HasDiscriminator().HasValue(10008);
                });

            modelBuilder.Entity("Koukei.Data.Entities.BaseItem", b =>
                {
                    b.HasOne("Koukei.Data.Entities.BaseItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Koukei.Data.Entities.BaseItem", "TopParent")
                        .WithMany()
                        .HasForeignKey("TopParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");

                    b.Navigation("TopParent");
                });

            modelBuilder.Entity("Koukei.Data.Entities.DocumentInfo", b =>
                {
                    b.HasOne("Koukei.Data.Entities.Document.Document", "Item")
                        .WithMany("DocumentInfo")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Koukei.Data.Entities.ImageInfo", b =>
                {
                    b.HasOne("Koukei.Data.Entities.Image.Image", "Item")
                        .WithMany("ImageInfo")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Koukei.Data.Entities.ItemGenre", b =>
                {
                    b.HasOne("Koukei.Data.Entities.Genre", "Genre")
                        .WithMany("ItemLinks")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Koukei.Data.Entities.BaseItem", "Item")
                        .WithMany("Genres")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Koukei.Data.Entities.ItemPerson", b =>
                {
                    b.HasOne("Koukei.Data.Entities.BaseItem", "Item")
                        .WithMany("RelatedPeople")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Koukei.Data.Entities.Person", "Person")
                        .WithMany("ItemLinks")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Koukei.Data.Entities.ItemRating", b =>
                {
                    b.HasOne("Koukei.Data.Entities.BaseItem", "Item")
                        .WithMany("Ratings")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Koukei.Data.Entities.Rating", "Rating")
                        .WithMany("ItemLinks")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("Koukei.Data.Entities.ItemStudio", b =>
                {
                    b.HasOne("Koukei.Data.Entities.BaseItem", "Item")
                        .WithMany("Studios")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Koukei.Data.Entities.Studio", "Studio")
                        .WithMany("ItemLinks")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("Koukei.Data.Entities.ItemTag", b =>
                {
                    b.HasOne("Koukei.Data.Entities.BaseItem", "Item")
                        .WithMany("Tags")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Koukei.Data.Entities.Tag", "Tag")
                        .WithMany("ItemLinks")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Koukei.Data.Entities.LinkedImage", b =>
                {
                    b.HasOne("Koukei.Data.Entities.BaseItem", "Item")
                        .WithMany("Images")
                        .HasForeignKey("ItemId");

                    b.HasOne("Koukei.Data.Entities.Person", "Person")
                        .WithMany("Images")
                        .HasForeignKey("PersonId");

                    b.HasOne("Koukei.Data.Entities.Studio", "Studio")
                        .WithMany("Images")
                        .HasForeignKey("StudioId");

                    b.Navigation("Item");

                    b.Navigation("Person");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("Koukei.Data.Entities.LinkedText", b =>
                {
                    b.HasOne("Koukei.Data.Entities.DocumentInfo", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId");

                    b.HasOne("Koukei.Data.Entities.Genre", "Genre")
                        .WithMany("Texts")
                        .HasForeignKey("GenreId");

                    b.HasOne("Koukei.Data.Entities.ImageInfo", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.HasOne("Koukei.Data.Entities.BaseItem", "Item")
                        .WithMany("Texts")
                        .HasForeignKey("ItemId");

                    b.HasOne("Koukei.Data.Entities.Person", "Person")
                        .WithMany("Texts")
                        .HasForeignKey("PersonId");

                    b.HasOne("Koukei.Data.Entities.Rating", "Rating")
                        .WithMany("Texts")
                        .HasForeignKey("RatingId");

                    b.HasOne("Koukei.Data.Entities.Studio", "Studio")
                        .WithMany("Texts")
                        .HasForeignKey("StudioId");

                    b.HasOne("Koukei.Data.Entities.Tag", "Tag")
                        .WithMany("Texts")
                        .HasForeignKey("TagId");

                    b.Navigation("Document");

                    b.Navigation("Genre");

                    b.Navigation("Image");

                    b.Navigation("Item");

                    b.Navigation("Person");

                    b.Navigation("Rating");

                    b.Navigation("Studio");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Koukei.Data.Entities.MediaLibraryScan", b =>
                {
                    b.HasOne("Koukei.Data.Entities.MediaLibraryRoot", "LibraryRoot")
                        .WithMany("Scans")
                        .HasForeignKey("LibraryRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryRoot");
                });

            modelBuilder.Entity("Koukei.Data.Entities.MediaStreamInfo", b =>
                {
                    b.HasOne("Koukei.Data.Entities.BaseItem", "Item")
                        .WithMany("MediaStreams")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Koukei.Data.Entities.Audio.AudioBook.AudioBookSeries", b =>
                {
                    b.HasOne("Koukei.Data.Entities.Document.Book.BookSeries", "LinkedBookSeries")
                        .WithMany()
                        .HasForeignKey("LinkedBookSeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedBookSeries");
                });

            modelBuilder.Entity("Koukei.Data.Entities.Video.TV.TvSeason", b =>
                {
                    b.HasOne("Koukei.Data.Entities.Video.TV.TvSeries", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Koukei.Data.Entities.Audio.AudioBook.AudioBook", b =>
                {
                    b.HasOne("Koukei.Data.Entities.Audio.AudioBook.AudioBookSeries", "AudioBookSeries")
                        .WithMany()
                        .HasForeignKey("AudioBookSeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Koukei.Data.Entities.Document.Book.Book", "LinkedBook")
                        .WithMany()
                        .HasForeignKey("LinkedBookId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AudioBookSeries");

                    b.Navigation("LinkedBook");
                });

            modelBuilder.Entity("Koukei.Data.Entities.Audio.Music.Music", b =>
                {
                    b.HasOne("Koukei.Data.Entities.Audio.Music.MusicAlbum", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Koukei.Data.Entities.Audio.Radio.RadioEpisode", b =>
                {
                    b.HasOne("Koukei.Data.Entities.Audio.Radio.Radio", "Radio")
                        .WithMany()
                        .HasForeignKey("RadioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Radio");
                });

            modelBuilder.Entity("Koukei.Data.Entities.Document.Book.Book", b =>
                {
                    b.HasOne("Koukei.Data.Entities.Document.Book.BookSeries", "BookSeries")
                        .WithMany()
                        .HasForeignKey("BookSeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BookSeries");
                });

            modelBuilder.Entity("Koukei.Data.Entities.Video.Movie.Movie", b =>
                {
                    b.HasOne("Koukei.Data.Entities.Video.Movie.MovieSeries", "MovieSeries")
                        .WithMany()
                        .HasForeignKey("MovieSeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MovieSeries");
                });

            modelBuilder.Entity("Koukei.Data.Entities.Video.MusicVideo", b =>
                {
                    b.HasOne("Koukei.Data.Entities.Audio.Music.Music", "LinkedMusic")
                        .WithMany()
                        .HasForeignKey("LinkedMusicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedMusic");
                });

            modelBuilder.Entity("Koukei.Data.Entities.Video.TV.TvEpisode", b =>
                {
                    b.HasOne("Koukei.Data.Entities.Video.TV.TvSeason", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Koukei.Data.Entities.Video.TV.TvSeries", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Season");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Koukei.Data.Entities.Document.Journal.JournalIssue", b =>
                {
                    b.HasOne("Koukei.Data.Entities.Document.Journal.Journal", "Journal")
                        .WithMany()
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Journal");
                });

            modelBuilder.Entity("Koukei.Data.Entities.Document.Magazine.MagazineIssue", b =>
                {
                    b.HasOne("Koukei.Data.Entities.Document.Magazine.Magazine", "Magazine")
                        .WithMany()
                        .HasForeignKey("MagazineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Magazine");
                });

            modelBuilder.Entity("Koukei.Data.Entities.Document.Newspaper.NewspaperIssue", b =>
                {
                    b.HasOne("Koukei.Data.Entities.Document.Newspaper.Newspaper", "Newspaper")
                        .WithMany()
                        .HasForeignKey("NewspaperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Newspaper");
                });

            modelBuilder.Entity("Koukei.Data.Entities.BaseItem", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Genres");

                    b.Navigation("Images");

                    b.Navigation("MediaStreams");

                    b.Navigation("Ratings");

                    b.Navigation("RelatedPeople");

                    b.Navigation("Studios");

                    b.Navigation("Tags");

                    b.Navigation("Texts");
                });

            modelBuilder.Entity("Koukei.Data.Entities.Genre", b =>
                {
                    b.Navigation("ItemLinks");

                    b.Navigation("Texts");
                });

            modelBuilder.Entity("Koukei.Data.Entities.MediaLibraryRoot", b =>
                {
                    b.Navigation("Scans");
                });

            modelBuilder.Entity("Koukei.Data.Entities.Person", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("ItemLinks");

                    b.Navigation("Texts");
                });

            modelBuilder.Entity("Koukei.Data.Entities.Rating", b =>
                {
                    b.Navigation("ItemLinks");

                    b.Navigation("Texts");
                });

            modelBuilder.Entity("Koukei.Data.Entities.Studio", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("ItemLinks");

                    b.Navigation("Texts");
                });

            modelBuilder.Entity("Koukei.Data.Entities.Tag", b =>
                {
                    b.Navigation("ItemLinks");

                    b.Navigation("Texts");
                });

            modelBuilder.Entity("Koukei.Data.Entities.Document.Document", b =>
                {
                    b.Navigation("DocumentInfo");
                });

            modelBuilder.Entity("Koukei.Data.Entities.Image.Image", b =>
                {
                    b.Navigation("ImageInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
