<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SoundFlow" Version="1.4.1" />
    <PackageReference Include="SoundFlow.Codecs.FFMpeg" Version="1.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Koukei.Ffmpeg\Koukei.Ffmpeg.csproj" />
  </ItemGroup>

</Project>
